

import Head from 'next/head'
import styles from './layout.module.css'
import Header from '../components/header'

const name = 'jfioqpjfkdsja;fdja;fjas'
export const siteTitle = 'Next.js Sample Website'

export default function Layout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Head>
        <title>Minting Tool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/v3.svg" />
      </Head>
      <main className={styles.main}>
        <Header />
        {children}
      </main>
    </>
  )
}